from app.ui.widgets.actions import control_actions
import cv2
from app.helpers.typing_helper import LayoutDictTypes

SETTINGS_LAYOUT_DATA: LayoutDictTypes = {
    'Appearance': {
        'ThemeSelection': {
            'level': 1,
            'label': '主题',
            'options': ['Dark', 'Dark-Blue', 'Light'],
            'default': 'Dark',
            'help': '选择要使用的主题',
            'exec_function': control_actions.change_theme,
            'exec_function_args': [],
        },
    },
    'General': {
        'ProvidersPrioritySelection': {
            'level': 1,
            'label': '提供者优先级',
            'options': ['CUDA', 'TensorRT', 'TensorRT-Engine', 'CPU'],
            'default': 'CUDA',
            'help': '选择系统中使用的提供者优先级。',
            'exec_function': control_actions.change_execution_provider,
            'exec_function_args': [],
        },
        'nThreadsSlider': {
            'level': 1,
            'label': '线程数',
            'min_value': '1',
            'max_value': '30',
            'default': '2',
            'step': 1,
            'help': '设置播放和录制时的执行线程数。强烈依赖GPU显存。',
            'exec_function': control_actions.change_threads_number,
            'exec_function_args': [],
        },
    },
    'Video Settings': {
        'VideoPlaybackCustomFpsToggle': {
            'level': 1,
            'label': '设置自定义视频播放帧率',
            'default': False,
            'help': '手动设置播放视频时使用的帧率',
            'exec_function': control_actions.set_video_playback_fps,
            'exec_function_args': [],
        },
        'VideoPlaybackCustomFpsSlider': {
            'level': 2,
            'label': '视频播放帧率',
            'min_value': '1',
            'max_value': '120',
            'default': '30',
            'parentToggle': 'VideoPlaybackCustomFpsToggle',
            'requiredToggleValue': True,
            'step': 1,
            'help': '设置视频播放时的最大帧率'
        },
    },
    'Auto Swap': {
        'AutoSwapToggle': {
            'level': 1,
            'label': '自动交换',
            'default': False,
            'help': '加载视频/图像文件时，使用选定的源面部/嵌入自动交换所有面部'
        },
    },
    'Beauty (PixelFree)': {
        'BeautyEnableToggle': {
            'level': 1,
            'label': '启用 PixelFree 美颜',
            'default': False,
            'help': '开启后会在最终输出帧上调用 PixelFree SDK 进行美颜处理',
        },
        'BeautyRotationSelection': {
            'level': 2,
            'label': '输入旋转角度',
            'options': ['0', '90', '180', '270'],
            'default': '0',
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': '若素材已经旋转，请指定角度以保持人脸方向正确',
        },
        'BeautyEyeStrengthSlider': {
            'level': 2,
            'label': '大眼',
            'min_value': '0',
            'max_value': '100',
            'default': '30',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_EyeStrength，大眼效果强度',
        },
        'BeautyThinFaceSlider': {
            'level': 2,
            'label': '瘦脸',
            'min_value': '0',
            'max_value': '100',
            'default': '40',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_thinning，调整脸部宽度',
        },
        'BeautyNarrowFaceSlider': {
            'level': 2,
            'label': '窄脸',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_narrow，控制脸型左右收紧',
        },
        'BeautyChinSlider': {
            'level': 2,
            'label': '下巴',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_chin，中心 50 为自然值',
        },
        'BeautyVFaceSlider': {
            'level': 2,
            'label': 'V 脸',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_V，调节下颌线以获得 V 脸',
        },
        'BeautySmallFaceSlider': {
            'level': 2,
            'label': '小脸',
            'min_value': '0',
            'max_value': '100',
            'default': '40',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_small，整体缩小脸部比例',
        },
        'BeautyNoseSlider': {
            'level': 2,
            'label': '鼻子',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_nose，调节鼻梁宽度/高度',
        },
        'BeautyForeheadSlider': {
            'level': 2,
            'label': '额头',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_forehead，中心值 50 为自然额头',
        },
        'BeautyMouthSlider': {
            'level': 2,
            'label': '嘴型',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_mouth，调节嘴巴厚度',
        },
        'BeautyPhiltrumSlider': {
            'level': 2,
            'label': '人中',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_philtrum，人中长度（50 为基准）',
        },
        'BeautyLongNoseSlider': {
            'level': 2,
            'label': '长鼻',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_long_nose，调整鼻子长度',
        },
        'BeautyEyeSpaceSlider': {
            'level': 2,
            'label': '眼距',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_eye_space，控制双眼间距',
        },
        'BeautySmileSlider': {
            'level': 2,
            'label': '微笑',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_smile，嘴角上扬幅度',
        },
        'BeautyEyeRotateSlider': {
            'level': 2,
            'label': '眼睛旋转',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_eye_rotate，调整眼睛倾斜',
        },
        'BeautyCanthusSlider': {
            'level': 2,
            'label': '开眼角',
            'min_value': '0',
            'max_value': '100',
            'default': '40',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFace_canthus，拉伸眼角',
        },
        'BeautySmoothSlider': {
            'level': 2,
            'label': '磨皮',
            'min_value': '0',
            'max_value': '100',
            'default': '35',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceBlurStrength，皮肤平滑',
        },
        'BeautyWhitenSlider': {
            'level': 2,
            'label': '美白',
            'min_value': '0',
            'max_value': '100',
            'default': '30',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceWhitenStrength，肤色提亮',
        },
        'BeautyRuddySlider': {
            'level': 2,
            'label': '红润',
            'min_value': '0',
            'max_value': '100',
            'default': '20',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceRuddyStrength，面部红润度',
        },
        'BeautySharpenSlider': {
            'level': 2,
            'label': '锐化',
            'min_value': '0',
            'max_value': '100',
            'default': '10',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceSharpenStrength，增强细节清晰度',
        },
        'BeautyNewWhitenSlider': {
            'level': 2,
            'label': '新美白',
            'min_value': '0',
            'max_value': '100',
            'default': '20',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceM_newWhitenStrength，新算法美白',
        },
        'BeautyQualitySlider': {
            'level': 2,
            'label': '画质增强',
            'min_value': '0',
            'max_value': '100',
            'default': '0',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceH_qualityStrength，整体画质提升',
        },
        'BeautyEyeBrightSlider': {
            'level': 2,
            'label': '亮眼',
            'min_value': '0',
            'max_value': '100',
            'default': '25',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterTypeFaceEyeBrighten，眼睛提亮',
        },
        'BeautyFilterStrengthSlider': {
            'level': 2,
            'label': '滤镜强度',
            'min_value': '0',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterStrength，控制滤镜整体强度',
        },
        'BeautyFilterNameText': {
            'level': 2,
            'label': '滤镜名称',
            'default': '',
            'width': 220,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterName，填写 bundle 内置滤镜 ID，如 heibai1',
        },
        'BeautyStickerSlider': {
            'level': 2,
            'label': '2D 贴纸',
            'min_value': '0',
            'max_value': '100',
            'default': '0',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterSticker2DFilter，贴纸强度/混合比例',
        },
        'BeautyExtendSlider': {
            'level': 2,
            'label': '扩展字段',
            'min_value': '0',
            'max_value': '100',
            'default': '0',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFiterExtend，保留用于 SDK 扩展',
        },
        'BeautyNasolabialSlider': {
            'level': 2,
            'label': '祛法令纹',
            'min_value': '0',
            'max_value': '100',
            'default': '0',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFilterNasolabial，减淡法令纹强度',
        },
        'BeautyBlackEyeSlider': {
            'level': 2,
            'label': '祛黑眼圈',
            'min_value': '0',
            'max_value': '100',
            'default': '0',
            'step': 1,
            'parentToggle': 'BeautyEnableToggle',
            'requiredToggleValue': True,
            'help': 'PFBeautyFilterBlackEye，去除黑眼圈',
        },
        'BeautyDllPathText': {
            'level': 1,
            'label': 'PixelFree DLL 路径',
            'default': 'dependencies/pixel_free/PixelFree.dll',
            'width': 320,
            'help': 'PixelFree.dll 的完整路径，修改后按回车立即生效',
            'exec_function': control_actions.reload_pixel_free_engine,
            'exec_function_args': [],
        },
        'BeautyAuthPathText': {
            'level': 1,
            'label': '授权文件路径',
            'default': 'dependencies/pixel_free/pixelfreeAuth.lic',
            'width': 320,
            'help': 'pixelfreeAuth.lic 的完整路径，修改后按回车立即生效',
            'exec_function': control_actions.reload_pixel_free_engine,
            'exec_function_args': [],
        },
        'BeautyFilterPathText': {
            'level': 1,
            'label': '滤镜 bundle 路径',
            'default': 'dependencies/pixel_free/filter_model.bundle',
            'width': 320,
            'help': 'filter_model.bundle 的完整路径，修改后按回车立即生效',
            'exec_function': control_actions.reload_pixel_free_engine,
            'exec_function_args': [],
        },
    },
    'Detectors': {
        'DetectorModelSelection': {
            'level': 1,
            'label': '面部检测模型',
            'options': ['RetinaFace', 'Yolov8', 'SCRFD', 'Yunet'],
            'default': 'RetinaFace',
            'help': '选择用于在输入图像或视频中检测面部的面部检测模型。'
        },
        'DetectorScoreSlider': {
            'level': 1,
            'label': '检测得分',
            'min_value': '1',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'help': '设置面部检测的置信度得分阈值。值越高，检测越自信，但可能错过一些面部。'
        },
        'MaxFacesToDetectSlider': {
            'level': 1,
            'label': '最大检测面部数',
            'min_value': '1',
            'max_value': '50',
            'default': '20',
            'step': 1,
            'help': '设置一帧中检测的最大面部数量'
        },
        'AutoRotationToggle': {
            'level': 1,
            'label': '自动旋转',
            'default': False,
            'help': '自动旋转输入以检测各种方向的面部。'
        },
        'ManualRotationEnableToggle': {
            'level': 1,
            'label': '手动旋转',
            'default': False,
            'help': '旋转面部检测器以更好地检测不同角度的面部。'
        },
        'ManualRotationAngleSlider': {
            'level': 2,
            'label': '旋转角度',
            'min_value': '0',
            'max_value': '270',
            'default': '0',
            'step': 90,
            'parentToggle': 'ManualRotationEnableToggle',
            'requiredToggleValue': True,
            'help': '设置为输入面部角度，以帮助检测躺下/倒挂等情况。角度按顺时针读取。'
        },
        'LandmarkDetectToggle': {
            'level': 1,
            'label': '启用关键点检测',
            'default': False,
            'help': '启用或禁用面部关键点检测，用于优化面部对齐。'
        },
        'LandmarkDetectModelSelection': {
            'level': 2,
            'label': '关键点检测模型',
            'options': ['5', '68', '3d68', '98', '106', '203', '478'],
            'default': '203',
            'parentToggle': 'LandmarkDetectToggle',
            'requiredToggleValue': True,
            'help': '选择关键点检测模型，不同模型检测的面部关键点数量不同。'
        },
        'LandmarkDetectScoreSlider': {
            'level': 2,
            'label': '关键点检测得分',
            'min_value': '1',
            'max_value': '100',
            'default': '50',
            'step': 1,
            'parentToggle': 'LandmarkDetectToggle',
            'requiredToggleValue': True,
            'help': '设置面部关键点检测的置信度得分阈值。'
        },
        'DetectFromPointsToggle': {
            'level': 2,
            'label': '从关键点检测',
            'default': False,
            'parentToggle': 'LandmarkDetectToggle',
            'requiredToggleValue': True,
            'help': '启用从指定关键点检测面部。'
        },
        'ShowLandmarksEnableToggle': {
            'level': 1,
            'label': '显示关键点',
            'default': False,
            'help': '实时显示关键点。'
        },
        'ShowAllDetectedFacesBBoxToggle': {
            'level': 1,
            'label': '显示边界框',
            'default': False,
            'help': '为帧中检测到的所有面部绘制边界框'
        }
    },
    'DFM Settings': {
        'MaxDFMModelsSlider': {
            'level': 1,
            'label': '最大DFM模型数量',
            'min_value': '1',
            'max_value': '5',
            'default': '1',
            'step': 1,
            'help': "设置同时保存在内存中的最大DFM模型数量。根据你的GPU显存设置此值。"
        }
    },
    'Frame Enhancer': {
        'FrameEnhancerEnableToggle': {
            'level': 1,
            'label': '启用帧增强',
            'default': False,
            'help': '启用视频输入的帧增强以提升视觉质量。'
        },
        'FrameEnhancerTypeSelection': {
            'level': 2,
            'label': '帧增强类型',
            'options': ['RealEsrgan-x2-Plus', 'RealEsrgan-x4-Plus', 'RealEsr-General-x4v3', 'BSRGan-x2', 'BSRGan-x4', 'UltraSharp-x4', 'UltraMix-x4', 'DDColor-Artistic', 'DDColor', 'DeOldify-Artistic', 'DeOldify-Stable', 'DeOldify-Video'],
            'default': 'RealEsrgan-x2-Plus',
            'parentToggle': 'FrameEnhancerEnableToggle',
            'requiredToggleValue': True,
            'help': '根据内容和分辨率需求选择要应用的帧增强类型。'
        },
        'FrameEnhancerBlendSlider': {
            'level': 2,
            'label': '混合',
            'min_value': '0',
            'max_value': '100',
            'default': '100',
            'step': 1,
            'parentToggle': 'FrameEnhancerEnableToggle',
            'requiredToggleValue': True,
            'help': '将增强结果混合回原始帧。'
        },
    },
    'Webcam Settings': {
        'WebcamMaxNoSelection': {
            'level': 2,
            'label': '网络摄像头最大数量',
            'options': ['1', '2', '3', '4', '5', '6'],
            'default': '1',
            'help': '选择允许用于面部交换的网络摄像头流的最大数量。'
        },
        'WebcamBackendSelection': {
            'level': 2,
            'label': '网络摄像头后端',
            'options': ['Default', 'DirectShow', 'MSMF', 'V4L', 'V4L2', 'GSTREAMER'],
            'default': 'Default',
            'help': '选择访问网络摄像头输入的后端。'
        },
        'WebcamMaxResSelection': {
            'level': 2,
            'label': '网络摄像头分辨率',
            'options': ['480x360', '640x480', '1280x720', '1920x1080', '2560x1440', '3840x2160', 
            "720x1280", "1080x1920", "1440x2560", "2160x3840"],
            'default': '1280x720',
            'help': '选择网络摄像头输入的最大分辨率。'
        },
        'WebCamMaxFPSSelection': {
            'level': 2,
            'label': '网络摄像头帧率',
            'options': ['23', '30', '60'],
            'default': '30',
            'help': '设置网络摄像头输入的最大每秒帧数（FPS）。'
        },
    },
    'Virtual Camera': {
        'SendVirtCamFramesEnableToggle': {
            'level': 1,
            'label': '发送帧到虚拟摄像头',
            'default': False,
            'help': '将交换后的视频/网络摄像头输出发送到虚拟摄像头，以便在外部应用程序中使用',
            'exec_function': control_actions.toggle_virtualcam,
            'exec_function_args': [],
        },
        'VirtCamBackendSelection': {
            'level': 1,
            'label': '虚拟摄像头后端',
            'options': ['obs', 'unitycapture'],
            'default': 'obs',
            'help': '根据你设置的虚拟摄像头选择后端',
            'parentToggle': 'SendVirtCamFramesEnableToggle',
            'requiredToggleValue': True,
            'exec_function': control_actions.enable_virtualcam,
            'exec_funtion_args': [],
        },
    },
    'Face Recognition': {
        'RecognitionModelSelection': {
            'level': 1,
            'label': '识别模型',
            'options': ['Inswapper128ArcFace', 'SimSwapArcFace', 'GhostArcFace', 'CSCSArcFace'],
            'default': 'Inswapper128ArcFace',
            'help': '选择用于比较面部相似度的ArcFace模型。'
        },
        'SimilarityTypeSelection': {
            'level': 1,
            'label': '交换相似度类型',
            'options': ['Opal', 'Pearl', 'Optimal'],
            'default': 'Opal',
            'help': '选择面部交换过程中用于面部检测和匹配的相似度计算类型。'
        },
    },
    'Embedding Merge Method': {
        'EmbMergeMethodSelection': {
            'level': 1,
            'label': '嵌入合并方法',
            'options': ['Mean', 'Median'],
            'default': 'Mean',
            'help': '选择合并面部嵌入的方法。"Mean"取平均值，"Median"取中间值，对异常值更稳健。'
        }
    },
    'Media Selection': {
        'TargetMediaFolderRecursiveToggle': {
            'level': 1,
            'label': '目标媒体包括子文件夹',
            'default': False,
            'help': '选择目标媒体文件夹时包括所有子文件夹中的文件'
        },
        'InputFacesFolderRecursiveToggle': {
            'level': 1,
            'label': '输入面部包括子文件夹',
            'default': False,
            'help': '选择输入面部文件夹时包括所有子文件夹中的文件'
        }
    }
}

CAMERA_BACKENDS = {
    'Default': cv2.CAP_ANY,
    'DirectShow': cv2.CAP_DSHOW,
    'MSMF': cv2.CAP_MSMF,
    'V4L': cv2.CAP_V4L,
    'V4L2': cv2.CAP_V4L2,
    'GSTREAMER': cv2.CAP_GSTREAMER,
}
